Repository CreamDeLaCream/creme-client, pull requests merged in 2022-03, with the labels that each got.

#49 오피스아워 전 머지
  src/common/components/Container.js
  src/common/components/Grid.js
  src/common/components/Modal.js
  src/pages/AddPet/AddPetPage.js
  src/pages/AddPet/InputBox.js
  src/pages/AddPet/MyPetData.js
  src/pages/MyPet/AddPetModal.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/Record.js
  src/pages/MyPet/UserCard.js
  yarn.lock
Labels: enhancement, ui/ux, setting

#56 마지막주 전 머지
  package-lock.json
  package.json
  src/common/components/Logo.js
  src/pages/MyPet/AnalysisData.js
  src/pages/MyPet/EmotionButton.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MyPetSelectBox.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/Record.js
  src/pages/MyPet/UserCard.js
  src/pages/Team/TeamPage.js
  yarn.lock
Labels: ui/ux, to do, feedback

#57 드롭존 컴포넌트 분리, 소셜로그인 구현, 중간 리뷰 반영
  .env.example
  src/App.js
  src/common/components/Button.js
  src/common/components/Dropzone.js
  src/common/components/Grid.js
  src/common/components/Header.js
  src/common/components/Image.js
  src/common/components/Logo.js
  src/common/components/Preview.js
  src/common/components/index.js
  src/common/redux/configureStore.js
  src/common/redux/modules/memo.js
  src/common/redux/modules/petimage.js
  src/common/redux/modules/post.js
  src/common/redux/modules/user.js
  src/common/utils/Cookie.js
  src/common/utils/OAuth.js
  src/index.js
  src/pages/Login/KakaoRedirect.js
  src/pages/Main/MainPage.js
  src/pages/Result/CopyURL.js
  src/pages/Result/ResultPage.js
  src/pages/index.js
Labels: enhancement, feedback

#72 오피스 아워 전 머지
  package-lock.json
  package.json
  public/Image/dog11.png
  public/Image/team.jpg
  src/common/components/AnimatedKeyword.js
  src/common/components/Circle.js
  src/common/components/Dropdown.js
  src/common/components/Header.js
  src/common/components/Input.js
  src/common/components/InputBox.js
  src/common/components/Modal.js
  src/common/components/MyPetKeywordsData.js
  src/common/components/Navbar.js
  src/common/components/Preview.js
  src/common/components/UserKeywordsData.js
  src/pages/AddPet/AddPetPage.js
  src/pages/AddPet/InputBox.js
  src/pages/AddUserLife/AddUserLifePage.js
  src/pages/AddUserLife/InputBox.js
  src/pages/AddUserLife/LifeStyleBox.js
  src/pages/Intro/Deck/1.jpeg
  src/pages/Intro/Deck/2.jpeg
  src/pages/Intro/Deck/3.jpeg
  src/pages/Intro/Deck/Deck.js
  src/pages/Intro/Deck/styles.css
  src/pages/Intro/Intro1st.js
  src/pages/Intro/Intro2nd.js
  src/pages/Intro/Intro3rd.js
  src/pages/Main/HowTo.js
  src/pages/Main/MainPage.js
  src/pages/MyPet/DogDataSet.js
  src/pages/MyPet/FilterMyPet.js
  src/pages/MyPet/FilterRecord.js
  src/pages/MyPet/MyPetImages.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/PetListButton.js
  src/pages/MyPet/Record.js
  src/pages/MyPet/UserCard.js
  src/pages/Result/ResultPage.js
  src/pages/Team/TeamMembers.js
  src/pages/Team/TeamPage.js
  yarn.lock
Labels: bug, enhancement, infra, ui/ux

#77 분석 페이지, 결과 페이지 api 연동
  src/common/components/Header.js
  src/common/redux/modules/analysis.js
  src/common/redux/modules/petimage.js
  src/common/redux/modules/user.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Main/HowTo.js
  src/pages/Main/SelectPetName.js
  src/pages/Result/Dropdown.js
  src/pages/Result/ResultPage.js
  src/pages/Team/MembersData.js
Labels: enhancement

#80 메인 페이지 반응형 수정, 로그인 새로고침시 유지 기능 추가, 결과 페이지 이미지 버그 해결
  package.json
  src/App.js
  src/common/components/Circle.js
  src/common/components/Grid.js
  src/common/components/Header.js
  src/common/components/Preview.js
  src/common/redux/modules/analysis.js
  src/common/redux/modules/user.js
  src/common/utils/Cookie.js
  src/pages/Analysis/EmotionTest.js
  src/pages/Intro/Deck/Deck.js
  src/pages/Main/MainPage.js
  src/pages/Main/SelectPetName.js
  yarn.lock
Labels: enhancement

#89 마지막 오피스아워 전 머지
  package.json
  src/common/components/MyPetData.js
  src/common/redux/configureStore.js
  src/pages/Intro/Deck/Deck.js
  src/pages/MyPet/AnalysisData.js
  src/pages/MyPet/FilterMyPet.js
  src/pages/MyPet/MyPet.js
  src/pages/MyPet/MyPetImages.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MyPetSelectBox.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/UserCard.js
  yarn.lock
Labels: to do

#91 결과 페이지 버그 수정, 좋아요 기능 추가
  package.json
  src/App.js
  src/common/components/AnimatedKeyword.js
  src/common/components/Dropdown.js
  src/common/components/Header.js
  src/common/components/Input.js
  src/common/redux/modules/analysis.js
  src/common/redux/modules/memo.js
  src/common/redux/modules/petimage.js
  src/common/redux/modules/user.js
  src/common/utils/Cookie.js
  src/pages/AddPet/AddPetPage.js
  src/pages/AddUserLife/AddUserLifePage.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Intro/Intro1st.js
  src/pages/Intro/Intro2nd.js
  src/pages/Main/MainPage.js
  src/pages/Main/SelectPetName.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/PetListButton.js
  src/pages/MyPet/UserCard.js
  src/pages/Result/ResultData.js
  src/pages/Result/ResultPage.js
Labels: bug, enhancement

#93 발표 전 마지막 머지
  src/common/components/Header.js
  src/common/components/Members.js
  src/common/redux/modules/analysis.js
  src/common/redux/modules/memo.js
  src/common/redux/modules/user.js
  src/pages/AddPet/AddPetPage.js
  src/pages/AddPet/InputBoxBirth.js
  src/pages/AddUserLife/AddUserLifePage.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Analysis/EmotionTest.js
  src/pages/Intro/Intro2nd.js
  src/pages/Login/KakaoRedirect.js
  src/pages/MyPet/AnalysisData.js
  src/pages/MyPet/DogDataSet.js
  src/pages/MyPet/EmotionButton.js
  src/pages/MyPet/FilterMyPet.js
  src/pages/MyPet/MyPetImages.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/Record.js
  src/pages/MyPet/UserCard.js
  src/pages/Result/Dropdown.js
  src/pages/Result/Keywords.js
  src/pages/Result/ResultData.js
  src/pages/Result/ResultPage.js
  yarn.lock
Labels: hot-fix, infra

#94 전체적인 로직 이슈 수정
  .env.example
  src/App.js
  src/common/components/MyPetData.js
  src/common/components/Text.js
  src/common/redux/modules/memo.js
  src/common/redux/modules/petimage.js
  src/common/redux/modules/user.js
  src/common/styles/textStyle.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Intro/Intro1st.js
  src/pages/Intro/Intro2nd.js
  src/pages/Intro/Intro3rd.js
  src/pages/Intro/IntroPage.js
  src/pages/Main/HowTo.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/emotionData1st.js
  src/pages/MyPet/emotionData2nd.js
  src/pages/Result/ResultItems.js
  src/pages/Result/SolutionItems.js
  src/pages/Result/Textarea.js
Labels: enhancement
