Repository CreamDeLaCream/creme-client, pull requests merged in 2022-02, with the labels that each got.

#7 Add `github to gitlab` GitHub action
  .github/workflows/github-to-gitlab.yml
Labels: enhancement

#12 Feature/lea
  public/Image/image0.png
  public/Image/image1.png
  public/Image/image2.png
  public/Image/image3.png
  public/Image/image4.png
  public/Image/image5.png
  src/common/components/Members.js
  src/common/styles/GlobalStyle.js
  src/common/styles/ServeFont.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Analysis/TestItems.js
  src/pages/Team/MembersData.js
Labels: enhancement

#13 Feature/kjy
  package.json
  public/index.html
  src/App.js
  src/common/components/Button.js
  src/common/components/Container.js
  src/common/components/Grid.js
  src/common/components/Header.js
  src/common/components/Image.js
  src/common/components/Input.js
  src/common/components/Logo.js
  src/common/components/NavItems.js
  src/common/components/NavMenu.js
  src/common/components/Navbar.js
  src/common/components/Template.js
  src/common/components/Text.js
  src/common/components/index.js
  src/common/styles/textStyle.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Analysis/Container.js
  src/pages/Intro/Container.js
  src/pages/Intro/IntroPage.js
  src/pages/Main/MainPage.js
  src/pages/MyPet/Container.js
  src/pages/MyPet/MyPetPage.js
  src/pages/Result/Container.js
  src/pages/Result/ResultPage.js
  src/pages/Team/Container.js
  src/pages/Team/TeamPage.js
  yarn.lock
Labels: enhancement

#25 2차 병합 - UI, 발표 전 전체적인 메인 기능 구현
  public/Image/cat0.png
  public/Image/dog0.png
  public/Image/dog1.gif
  public/Image/dog2.gif
  public/Image/dog3.gif
  public/Image/dog4.gif
  public/Image/dog5.gif
  public/Image/dog6.gif
  public/Image/dog7.gif
  public/Image/image1.png
  public/Image/image2.png
  public/Image/image5.png
  src/common/components/Container.js
  src/common/components/Dropdown.js
  src/common/components/Header.js
  src/common/components/Keyword.js
  src/common/components/KeywordData.js
  src/common/components/Navbar.js
  src/common/styles/GlobalStyle.js
  src/pages/Analysis/AnalysisPage.js
  src/pages/Analysis/EmotionTest.js
  src/pages/Analysis/Loading.js
  src/pages/Analysis/TestItems.js
  src/pages/Intro/IntroPage.js
  src/pages/MyPet/AnalysisData.js
  src/pages/MyPet/MyPet.js
  src/pages/MyPet/MyPetImages.js
  src/pages/MyPet/MyPetInfo.js
  src/pages/MyPet/MyPetList.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/Plusbutton.js
  src/pages/MyPet/Record.js
  src/pages/Team/MembersData.js
  src/pages/Team/MembersIamges.js
  src/pages/Team/TeamMembers.js
  src/pages/Team/TeamPage.js
Labels: enhancement, ui/ux

#33 오피스아워 전 머지
  public/Image/bgdog0.png
  public/Image/bgdog1.png
  public/Image/bgdog2.png
  public/Image/image3.png
  public/Image/image4.png
  public/Image/partner1.png
  public/Image/useinfo.png
  public/favicon.ico
  src/App.js
  src/common/components/Input.js
  src/common/components/Keyword.js
  src/common/components/KeywordData.js
  src/common/components/Modal.js
  src/common/components/NavItems.js
  src/common/components/Navbar.js
  src/common/styles/GlobalStyle.js
  src/common/styles/HighlightText.js
  src/common/styles/ServeFont.js
  src/pages/Analysis/EmotionTest.js
  src/pages/Intro/Intro1st.js
  src/pages/Intro/Intro2nd.js
  src/pages/Intro/Intro3rd.js
  src/pages/Intro/Intro4th.js
  src/pages/Intro/IntroPage.js
  src/pages/Intro/PatternCheck.js
  src/pages/Intro/UserKeywords.js
  src/pages/Main/MainPage.js
  src/pages/MyPet/MyPetImages.js
  src/pages/MyPet/MyPetInfo.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/UserCard.js
  src/pages/Result/ResultPage.js
  src/pages/Team/MembersData.js
  src/pages/Team/TeamMembers.js
  src/pages/Team/TeamPage.js
  yarn.lock
Labels: enhancement, ui/ux, setting

#34 3차 병합 - 결과 페이지 기능 추가 및 더미 데이터 생성
  package.json
  src/common/components/Grid.js
  src/common/components/Header.js
  src/common/components/Input.js
  src/pages/Main/MainPage.js
  src/pages/Result/BarChart.js
  src/pages/Result/Dropdown.js
  src/pages/Result/ResultData.js
  src/pages/Result/ResultPage.js
  yarn.lock
Labels: enhancement

#42 1차 발표 전 프론트엔드 머지
  public/Image/partner2.png
  src/common/components/Keyword.js
  src/common/components/KeywordData.js
  src/common/components/MyPetData.js
  src/common/styles/GlobalStyle.js
  src/pages/Analysis/EmotionTest.js
  src/pages/Intro/Intro3rd.js
  src/pages/Intro/IntroPage.js
  src/pages/MyPet/MyPetImages.js
  src/pages/MyPet/MyPetList.js
  src/pages/MyPet/MyPetPage.js
  src/pages/MyPet/MypetCard.js
  src/pages/MyPet/PetListButton.js
  src/pages/MyPet/Record.js
  src/pages/Result/ResultPage.js
  yarn.lock
Labels: enhancement, ui/ux, to-do

#43 차트 기능 추가 및 addPet, addUserLife
  package.json
  src/App.js
  src/common/components/Circle.js
  src/common/components/Container.js
  src/common/components/Dropdown.js
  src/common/components/Header.js
  src/common/components/Input.js
  src/common/components/Modal.js
  src/common/components/Text.js
  src/common/components/index.js
  src/common/redux/modules/userSlice.js
  src/common/redux/store.js
  src/common/styles/GlobalStyle.js
  src/common/styles/theme.js
  src/pages/AddPet/AddPetPage.js
  src/pages/AddPet/InputBox.js
  src/pages/AddUserLife/AddUserLifePage.js
  src/pages/AddUserLife/InputBox.js
  src/pages/Main/LoginUser.js
  src/pages/Main/MainPage.js
  src/pages/Main/Visitor.js
  src/pages/Result/BarChart.js
  src/pages/Result/Dropdown.js
  src/pages/Result/ResultData.js
  src/pages/Result/ResultPage.js
  src/pages/index.js
  yarn.lock
Labels: enhancement, ui/ux
